"""
Developer: Matheus Martins da Silva
Creation Date: 11/2024
Contact Email: matheus.sql18@gmail.com
All rights reserved. This software is the property of Matheus Martins da Silva. No part of this software may be used, reproduced, distributed, or modified without the express written permission of the owner.
"""

import os
from threading import Lock
from typing import Optional, Tuple

import clr

from config.settings import settings

# Add the path to the directory containing the compiled DLL
dll_path = os.path.join(settings.BASE_DIR, "ThermalCameraLibrary")

clr.AddReference(os.path.join(dll_path, "ThermalCamera.dll"))
clr.AddReference(os.path.join(dll_path, "Flir.Atlas.Live.dll"))
clr.AddReference(os.path.join(dll_path, "Flir.Atlas.Image.dll"))
clr.AddReference("System")

import Flir.Atlas.Image as Image  # type: ignore
import System  # type: ignore
import System.Drawing as Drawing  # type: ignore


# TODO: review the class and methods - generated by AI
class IsothermsManager:
    """
    A class to manage Isotherms settings for Flir's Atlas SDK.

    Reference:
        https://update2flir2se.blob.core.windows.net/update/SSF/Atlas%20Cronos/docs/7.5.0/html/namespace_flir_1_1_atlas_1_1_image_1_1_isotherms.html
    """

    def __init__(self, _camera):
        """Initialize the Isotherms class."""
        self._camera = _camera
        self.logger = _camera.logger
        self._lock = _camera.service_lock

        self._image = _camera.image_obj_thermal
        self._visual_image = _camera.image_obj_visual

    @property
    def isotherm_type(self) -> Optional[Image.Isotherms.IsothermType]:
        """Get the isotherm type."""
        try:
            with self._lock:
                return self._image.Isotherms.IsothermType
        except Exception as e:
            self.logger.error(f"Failed to get isotherm type: {e}")
            return None

    @property
    def contrast_color(self) -> Optional[Drawing.Color]:
        """Get the contrast color."""
        try:
            with self._lock:
                return self._image.Isotherms.ContrastColor
        except Exception as e:
            self.logger.error(f"Failed to get contrast color: {e}")
            return None

    @property
    def appearance(self) -> Optional[Image.Isotherms.Appearance]:
        """Get the appearance."""
        try:
            with self._lock:
                return self._image.Isotherms.Appearance
        except Exception as e:
            self.logger.error(f"Failed to get appearance: {e}")
            return None

    @property
    def color(self) -> Optional[Drawing.Color]:
        """Get the color."""
        try:
            with self._lock:
                return self._image.Isotherms.Color
        except Exception as e:
            self.logger.error(f"Failed to get color: {e}")
            return None

    def add_above_isotherm(self) -> Optional[Image.Isotherms.AlarmIsothermAbove]:
        """
        Add an above isotherm to the image.

        Returns:
            Optional[Image.Isotherms.AlarmIsothermAbove]: The added isotherm
        """
        try:
            with self._lock:
                isotherm = self._image.Isotherms.AddAbove()
                self.logger.info("Above isotherm added.")
                return isotherm
        except Exception as e:
            self.logger.error(f"Failed to add above isotherm: {e}")
            return None

    def add_below_isotherm(self) -> Optional[Image.Isotherms.AlarmIsothermBelow]:
        """
        Add a below isotherm to the image.

        Returns:
            Optional[Image.Isotherms.AlarmIsothermBelow]: The added isotherm
        """
        try:
            with self._lock:
                isotherm = self._image.Isotherms.AddBelow()
                self.logger.info("Below isotherm added.")
                return isotherm
        except Exception as e:
            self.logger.error(f"Failed to add below isotherm: {e}")
            return None

    def add_interval_isotherm(self) -> Optional[Image.Isotherms.AlarmIsothermInterval]:
        """
        Add an interval isotherm to the image.

        Returns:
            Optional[Image.Isotherms.AlarmIsothermInterval]: The added isotherm
        """
        try:
            with self._lock:
                isotherm = self._image.Isotherms.AddInterval()
                self.logger.info("Interval isotherm added.")
                return isotherm
        except Exception as e:
            self.logger.error(f"Failed to add interval isotherm: {e}")
            return None

    def remove_isotherm(self, isotherm: Image.Isotherms.Isotherm) -> bool:
        """
        Remove an isotherm from the image.

        Args:
            isotherm (Image.Isotherms.Isotherm): The isotherm to remove

        Returns:
            bool: True if successful, False otherwise
        """
        try:
            with self._lock:
                self._image.Isotherms.Remove(isotherm)
                self.logger.info("Isotherm removed.")
                return True
        except Exception as e:
            self.logger.error(f"Failed to remove isotherm: {e}")
            return False

    def get_interval_min_max(
        self, isotherm: Image.Isotherms.Isotherm
    ) -> Optional[Tuple[float, float]]:
        """
        Get the minimum and maximum values for the isotherm interval.

        Args:
            isotherm (Image.Isotherms.Isotherm): The isotherm to get values from

        Returns:
            Optional[Tuple[float, float]]: Tuple containing (min, max) values or None if failed
        """
        try:
            with self._lock:
                min_val = System.Double(0)
                max_val = System.Double(0)
                isotherm.GetIntervalMinMaxValues(min_val, max_val)
                return (float(min_val), float(max_val))
        except Exception as e:
            self.logger.error(f"Failed to get interval min/max values: {e}")
            return None

    def set_isotherm_color(
        self, isotherm: Image.Isotherms.Isotherm, color: Drawing.Color
    ) -> bool:
        """
        Set the color of an isotherm.

        Args:
            isotherm (Image.Isotherms.Isotherm): The isotherm to modify
            color (Drawing.Color): The color to set

        Returns:
            bool: True if successful, False otherwise
        """
        try:
            with self._lock:
                isotherm.Color = color
                self.logger.info(f"Isotherm color set to {color}.")
                return True
        except Exception as e:
            self.logger.error(f"Failed to set isotherm color: {e}")
            return False

    def set_threshold(
        self, isotherm: Image.Isotherms.AlarmIsothermAbove, threshold: float
    ) -> bool:
        """
        Set the threshold value for an above/below isotherm.

        Args:
            isotherm (Image.Isotherms.AlarmIsothermAbove): The isotherm to modify
            threshold (float): The threshold value to set

        Returns:
            bool: True if successful, False otherwise
        """
        try:
            with self._lock:
                isotherm.Threshold = threshold
                self.logger.info(f"Isotherm threshold set to {threshold}.")
                return True
        except Exception as e:
            self.logger.error(f"Failed to set isotherm threshold: {e}")
            return False

    def to_string(self) -> dict:
        """
        Return all properties in JSON format.

        Returns:
            dict: Dictionary containing the isotherm properties
        """
        return {
            "isotherm_type": self.isotherm_type,
            "contrast_color": self.contrast_color,
            "appearance": self.appearance,
            "color": self.color,
        }
